### ISSUE TITLE
Does not work with prompt-toolkit 3.0.9

### ISSUE THREAD

**Issue by zblz** [facultyai/faculty-sync#51]
Installing `faculty-sync` from scratch will pull prompt-toolkit 3.0.9, which leads to the following failure when trying to start `faculty-sync`:
```
Traceback (most recent call last):
  File "/Users/victor/.local/bin/faculty-sync", line 5, in <module>
    from faculty_sync import run
  File "/Users/victor/.local/pipx/venvs/faculty-sync/lib/python3.7/site-packages/faculty_sync/__init__.py", line 1, in <module>
    from .app import run  # noqa
  File "/Users/victor/.local/pipx/venvs/faculty-sync/lib/python3.7/site-packages/faculty_sync/app.py", line 8, in <module>
    from .ui import View
  File "/Users/victor/.local/pipx/venvs/faculty-sync/lib/python3.7/site-packages/faculty_sync/ui.py", line 11, in <module>
    from prompt_toolkit.eventloop import get_event_loop
ImportError: cannot import name 'get_event_loop' from 'prompt_toolkit.eventloop' (/Users/victor/.local/pipx/venvs/faculty-sync/lib/python3.7/site-packages/prompt_toolkit/eventloop/__init__.py)
```
Downgrading `prompt-toolkit` to 2.0.9 fixes it.

Might be worth reconsidering #14 for stability.

**Comment by pbugnion** [comment]
Thanks! 

Somewhat fixed in #50 , which I'll release soon.
Deeper thinking about prompt toolkit 3 support would be good.
